book_store/config/routes.rb
Rails.application.routes.draw do
  resources :publisher_houses
  resources :authors
  resources :books
  
  get '/search', to: 'search#index'
  post '/collaboration', to: 'collaboration#create'
  delete '/collaboration', to: 'collaboration#destroy'

  root to: 'publisher_houses#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

book_store/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BookStore</title>
    <%= csrf_meta_tags %>
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/css?family=Great+Vibes" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Courgette" rel="stylesheet">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      <!-- MAIN MENU -->
      <header class="row">
        <div class="col-xs-12 text-center">
          <h1>My Dear Library</h1>
          <%= publisher_home_link %> |
          <%= authors_home_link %> |
          <%= books_home_link %>
        </div>
      </header>

      <div class="row">
        <hr class="col-xs-10 col-xs-offset-1">
      </div>

      <div class="row">
        <div class="col-xs-10 col-xs-offset-1">
          <%= form_tag(search_path, method: :get) do %>
            <div class="form-group">
              <%= text_field_tag :term, get_search_params(params), class: "form-control" %>
            </div>
          <% end %>
        </div>
      </div>
      
      <!-- MAIN CONTENT -->
      <div class="row">
        <div class="col-xs-10 col-xs-offset-1">
          
          <!-- NOTIFICATION ELEMENT   -->
          <% unless (notice.nil?) %>
          <div class="row">
            <div class="col-xs-12">
              <% if (flash[:color].nil?) %>
              <div class="alert alert-success" role="info">
              <% else %>
              <div class="alert alert-<%= flash[:color] %>" role="info">
              <% end %>
                <span><%= notice %></span>
              </div>
            </div>
          </div>
          <% end %>

          <!-- BREADCRUMB   -->
          <div class="row">
            <h2 class="col-xs-12"><%= yield(:breadcrumb) %></h2>  
          </div>

          <!-- MAIN CONTAINER -->
          <div class="row">
            <!-- DATA -->
            <div class="col-xs-10">
              <%= yield(:main) %>
            </div>
            <!-- CONTROLLS -->
            <div class="col-xs-2">
              <%= yield(:sidebar) %>
            </div>

          </div>
        
        </div>
      </div>

      <!-- FOOTER -->
      <div class="row">
        <div class="col-xs-12 text-center">
          <span>Andres Rojas Villalobos, :)</span>
        </div>
      </div>
    </div>
    
  </body>
</html>