book_store/config/routes.rb
Rails.application.routes.draw do
  resources :publisher_houses
  resources :authors
  resources :books
  
  get '/search', to: 'search#index'
  post '/collaboration', to: 'collaboration#create'
  delete '/collaboration', to: 'collaboration#destroy'

  root to: 'publisher_houses#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

book_store/app/models/author.rb
# Author Class
class Author < ApplicationRecord
  # Dependencies
  has_many :collaborations, dependent: :destroy
  has_many :books, through: :collaborations

  # Validations
  validates :first_name, presence: true, length: { minimum: 5, maximum: 35 }
  validates :last_name, presence: true, length: { minimum: 5, maximum: 50 }
  validates :birthdate, presence: true

  # Alias
  alias_attribute :search_name, :author_name

  ## Public Methods

  # Author name returns the last_name, first_name format
  def author_name
    "#{last_name}, #{first_name}"
  end

  # Get 3 random books for the current Author
  def sample_books
    books.sample(3).sort! { |a,b| a.title.downcase <=> b.title.downcase }
  end

  # books ordered by title
  def sort_books 
    books.order(:title)
  end
end

book_store/app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
  before_action :set_author, only: [:show, :edit, :update, :destroy]

  # GET /authors
  def index
    @authors = Author.includes(:books).all.order(:last_name)
  end

  # GET /authors/1
  def show
  end

  # GET /authors/new
  def new
    @author = Author.new
  end

  # GET /authors/1/edit
  def edit
  end

  # POST /authors
  def create
    @author = Author.new(author_params)

    respond_to do |format|
      if @author.save
        format.html { redirect_to(@author, notice: 'Author was successfully created.') }
      else
        format.html { render(:new) }
      end
    end
  end

  # PATCH/PUT /authors/1
  def update
    respond_to do |format|
      if @author.update(author_params)
        format.html { redirect_to(@author, notice: 'Author was successfully updated.') }
      else
        format.html { render(:edit) }
      end
    end
  end

  # DELETE /authors/1
  def destroy
    @author.destroy
    respond_to do |format|
      format.html { redirect_to(authors_url, notice: 'Author was successfully destroyed.', flash: {color: 'warning'}) }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_author
      @author = Author.includes(:books).find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def author_params
      params.require(:author).permit(:first_name, :last_name, :birthdate)
    end
end

book_store/app/helpers/authors_helper.rb
module AuthorsHelper
end

book_store/app/views/authors/_form.html.erb
<%= form_for(author) do |f| %>
<div class="col-xs-12">
  <div class="panel panel-success">
    <div class="panel-heading"><%= section_title("Author Information")%></div>
    <div class="panel-body">
      <% if (author.errors.any?) %>
        <div id="error_explanation">
          <h2><%= pluralize(author.errors.count, "error") %> prohibited this author from being saved:</h2>
          <ul>
          <% author.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
          </ul>
        </div>
      <% end %>

      <div class="form-group">
        <%= f.label :first_name %>
        <%= f.text_field :first_name, class: "form-control" %>
      </div>

      <div class="form-group">
        <%= f.label :last_name %>
        <%= f.text_field :last_name, class: "form-control" %>
      </div>

      <div class="form-group">
        <%= f.label :birthdate %>
        <%= f.date_select :birthdate, class: "form-control", start_year: 1900, end_year: Date.today.year %>
      </div>

    </div>
    <div class="panel-footer text-right">
      <%= save_button %> |
      <% if (author.id.nil?) %>
        <%= cancel_button(authors_path) %>
      <% else %>
        <%= cancel_button(author_path(author)) %>
      <% end %>
    </div>
  </div>
</div>
<% end %>

book_store/app/views/authors/edit.html.erb
<% content_for :breadcrumb do %>
  <h2 class="col-xs-12"><%= authors_home_link %> > <%= link_to(@author.author_name, @author) %> > Edit</h2>
<% end %>

<% content_for :main do %>
  <div class="row"> 
    <%= render 'form', author: @author %>
  </div>
<% end %>

book_store/app/views/authors/index.html.erb
<% content_for :breadcrumb do %>
  <h2 class="col-xs-12"><%= authors_home_link %> | Authors</h2>
<% end %>

<% content_for :main do %>
  <div class="row">
    <div class="col-xs-12">
      <%= render '/shared/panel', title: 'Our Authors', class_name: 'panel-success', big_title: true do %>
        <table class="table table-striped">
          <thead>
            <tr>
              <th>Name</th>
              <th>Birthdate</th>
              <th>Some of my Books</th>
            </tr>
          </thead>

          <tbody>
          <% @authors.each do |author| %>
            <tr>
              <td><%= link_to(author.author_name, author) %></td>
              <td><%= author.birthdate %></td>
              <td>
                <ul class="no-margin">
                <% author.sample_books.each do |book| %>
                  <li><%= link_to(book.title, book) %></li>
                <% end %>
                </ul>
              </td>
            </tr>
          <% end %>
          </tbody>
        </table>
      <% end %>
    </div>
  </div>
<% end %>

<% content_for :sidebar do %>
  <div class="row">
    <%= render '/shared/panel', title: 'Controls', class_name: 'panel-info', big_title: false do %>
      <%= create_icon_link_to(new_author_path) %>
    <% end %>
  </div>
<% end %>

book_store/app/views/authors/new.html.erb
<% content_for :breadcrumb do %>
  <h2 class="col-xs-12"><%= authors_home_link %> > New</h2>
<% end %>

<% content_for :main do %>
  <div class="row">
    <%= render 'form', author: @author %>
  </div>
<% end %>

book_store/app/views/authors/show.html.erb
<% content_for :breadcrumb do %>
  <h2 class="col-xs-12"><%= authors_home_link %> > <%= @author.author_name %></h2>
<% end %>

<% content_for :main do %>
  <div class="row">
    <div class="col-xs-12">
      <div class="panel panel-success">
        <div class="panel-heading"><%= section_title("My Details") %></div>
        <div class="panel-body">
          <p>
            <strong>First name:</strong>
            <%= @author.first_name %>
          </p>

          <p>
            <strong>Last name:</strong>
            <%= @author.last_name %>
          </p>

          <p>
            <strong>Birthdate:</strong>
            <%= @author.birthdate %>
          </p>
        </div>
      </div>
    </div>
  </div>

  <div class="row">
    <div class="col-xs-12">
      <%= render '/shared/panel', title: 'My Books', class_name: 'panel-info', big_title: true do %>
        <%= render '/shared/books_table', book_list: @author.sort_books %>
      <% end %>
    </div>   
  </div>

<% end %>

<% content_for :sidebar do %>
  <div class="row">
    <%= render '/shared/panel', title: 'Controls', class_name: 'panel-info', big_title: false do %>
      <%= edit_icon_link_to(edit_author_path(@author)) %> | 
      <%= delete_icon_link_to(@author) %>
    <% end %>
  </div>
<% end %>