book_store/config/routes.rb
Rails.application.routes.draw do
  resources :publisher_houses
  resources :authors
  resources :books
  
  get '/search', to: 'search#index'
  post '/collaboration', to: 'collaboration#create'
  delete '/collaboration', to: 'collaboration#destroy'

  root to: 'publisher_houses#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

book_store/app/controllers/publisher_houses_controller.rb
class PublisherHousesController < ApplicationController
  before_action :set_publisher_house, only: [:show, :edit, :update, :destroy]

  # GET /publisher_houses
  def index
    @publisher_houses = PublisherHouse.all.order(:name)
  end

  # GET /publisher_houses/1
  def show
  end

  # GET /publisher_houses/new
  def new
    @publisher_house = PublisherHouse.new
  end

  # GET /publisher_houses/1/edit
  def edit
  end

  # POST /publisher_houses
  def create
    @publisher_house = PublisherHouse.new(publisher_house_params)

    respond_to do |format|
      if @publisher_house.save
        format.html { redirect_to(@publisher_house, notice: 'Publisher house was successfully created.') }
      else
        format.html { render(:new) }
      end
    end
  end

  # PATCH/PUT /publisher_houses/1
  def update
    respond_to do |format|
      if @publisher_house.update(publisher_house_params)
        format.html { redirect_to(@publisher_house, notice: 'Publisher house was successfully updated.') }
      else
        format.html { render(:edit) }
      end
    end
  end

  # DELETE /publisher_houses/1
  def destroy
    @publisher_house.destroy
    respond_to do |format|
      format.html { redirect_to(publisher_houses_url, notice: 'Publisher house was successfully destroyed.', flash: {color: 'warning'}) }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_publisher_house
      @publisher_house = PublisherHouse.includes(:books).find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def publisher_house_params
      params.require(:publisher_house).permit(:name)
    end
end

book_store/app/helpers/publisher_houses_helper.rb
module PublisherHousesHelper
end

book_store/app/views/publisher_houses/_form.html.erb
<%= form_for(publisher_house) do |f| %>
<div class="col-xs-12">
  <div class="panel panel-success">
    <div class="panel-heading"><%= section_title("Publisher House Information")%></div>
    <div class="panel-body">
      <% if (publisher_house.errors.any?) %>
        <div id="error_explanation">
          <h2><%= pluralize(publisher_house.errors.count, "error") %> prohibited this publisher_house from being saved:</h2>
          <ul>
          <% publisher_house.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
          </ul>
        </div>
      <% end %>
      <div class="form-group">
        <%= f.label :name %>
        <%= f.text_field :name, class: "form-control" %>
      </div>
    </div>
    <div class="panel-footer text-right">
      <%= save_button %> |
      <% if (publisher_house.id.nil?) %>
        <%= cancel_button(publisher_houses_path) %>
      <% else %>
        <%= cancel_button(publisher_house_path(publisher_house)) %>
      <% end %>
    </div>
  </div>
</div>
<% end %>

book_store/app/views/publisher_houses/edit.html.erb
<% content_for :breadcrumb do %>
  <h2 class="col-xs-12"><%= publisher_home_link %> > <%= link_to(@publisher_house.name, publisher_house_path(@publisher_house)) %> > Edit</h2>
<% end %>

<% content_for :main do %>
  <div class="row">
    <%= render 'form', publisher_house: @publisher_house %>
  </div>
<% end %>

book_store/app/views/publisher_houses/index.html.erb
<% content_for :breadcrumb do %>
  <h2 class="col-xs-12"><%= publisher_home_link %> | Publisher Houses</h2>  
<% end %>

<% content_for :main do %>
  <div class="row">
    <div class="col-xs-12">
      <%= render '/shared/panel', title: 'Our Partners', class_name: 'panel-success', big_title: true do %>
        <table class="table table-striped">
          <thead>
            <tr>
              <th>Name</th>
            </tr>
          </thead>
          <tbody>
            <% @publisher_houses.each do |publisher_house| %>
              <tr>
                <td class="col-xs-12"><%= link_to(publisher_house.name, publisher_house) %></td>
              </tr>
            <% end %>
          </tbody>
        </table>
      <% end %>
    </div>
  </div>
<% end %>

<% content_for :sidebar do %>
  <div class="row">
    <%= render '/shared/panel', title: 'Controls', class_name: 'panel-info', big_title: false do %>
      <%= create_icon_link_to(new_publisher_house_path) %>
    <% end %>
  </div>
<% end %>

book_store/app/views/publisher_houses/new.html.erb
<% content_for :breadcrumb do %>
  <h2 class="col-xs-12"><%= publisher_home_link %> > New</h2>
<% end %>

<% content_for :main do %>
  <div class="row">
    <%= render 'form', publisher_house: @publisher_house %>
  </div>
<% end %>

book_store/app/views/publisher_houses/show.html.erb
<% content_for :breadcrumb do %>
  <h2 class="col-xs-12"><%= publisher_home_link %> > <%= @publisher_house.name %></h2>
<% end %>

<% content_for :main do %>
  <div class="row">
    <div class="col-xs-12">
      <%= render '/shared/panel', title: 'Our Books', class_name: 'panel-success', big_title: true do %>
        <%= render '/shared/books_table', book_list: @publisher_house.sort_books %>
      <% end %>
    </div>   
  </div>
<% end %>

<% content_for :sidebar do %>
  <div class="row">
    <%= render '/shared/panel', title: 'Controls', class_name: 'panel-info', big_title: false do %>
      <%= edit_icon_link_to(edit_publisher_house_path(@publisher_house)) %> | 
      <%= delete_icon_link_to(@publisher_house) %>
    <% end %>
  </div>
<% end %>