book_store/config/routes.rb
Rails.application.routes.draw do
  resources :publisher_houses
  resources :authors
  resources :books
  
  get '/search', to: 'search#index'
  post '/collaboration', to: 'collaboration#create'
  delete '/collaboration', to: 'collaboration#destroy'

  root to: 'publisher_houses#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

book_store/app/models/book.rb
# Book Class
class Book < ApplicationRecord
  # Dependencies
  belongs_to :publisher_house
  has_many :collaborations, dependent: :destroy
  has_many :authors, through: :collaborations

  # Validations
  validates :title, presence: true, uniqueness: true, length: { minimum: 10, maximum: 150 }
  validates :pages, presence: true, numericality: {only_integer: true, greater_than: 0}
  validates :cover, presence: true, url: true
  validates :published_at, presence: true

  # Alias
  alias_attribute :search_name, :title

  # sort authors by last name
  def sort_authors
    authors.order(:last_name)
  end
  
end

book_store/app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :set_book, only: [:show, :edit, :update, :destroy]

  # GET /books
  def index
    @books = Book.includes(:authors).all.order(:title)
  end

  # GET /books/1
  def show
    @authors = Author.all.order(:last_name) - @book.authors
    @collaboration = Collaboration.new
  end

  # GET /books/new
  def new
    @book = Book.new
    @houses = PublisherHouse.all.order(:name)
  end

  # GET /books/1/edit
  def edit
    @houses = PublisherHouse.all.order(:name)
  end

  # POST /books
  def create
    @book = Book.new(book_params)
    @houses = PublisherHouse.all.order(:name)

    respond_to do |format|
      if @book.save
        format.html { redirect_to(@book, notice: 'Book was successfully created.') }
      else
        format.html { render(:new) }
      end
    end
  end

  # PATCH/PUT /books/1
  def update
    respond_to do |format|
      if @book.update(book_params)
        format.html { redirect_to(@book, notice: 'Book was successfully updated.') }
      else
        format.html { render(:edit) }
      end
    end
  end

  # DELETE /books/1
  def destroy
    @book.destroy
    respond_to do |format|
      format.html { redirect_to(books_url, notice: 'Book was successfully destroyed.', flash: {color: 'warning'}) }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_book
      @book = Book.includes(:authors).find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def book_params
      params.require(:book).permit(:title, :pages, :cover, :published_at, :publisher_house_id)
    end
end

book_store/app/helpers/books_helper.rb
module BooksHelper
end

book_store/app/views/books/_form.html.erb
<%= form_for(book) do |f| %>
<div class="col-xs-12">
  <div class="panel panel-success">
    <div class="panel-heading"><%= section_title("Book Information")%></div>
    <div class="panel-body">
      <% if (book.errors.any?) %>
        <div id="error_explanation">
          <h2><%= pluralize(book.errors.count, "error") %> prohibited this book from being saved:</h2>
          <ul>
          <% book.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
          </ul>
        </div>
      <% end %>

      <div class="form-group">
        <%= f.label :title %>
        <%= f.text_field :title, class: "form-control" %>
      </div>

      <div class="form-group">
        <%= f.label :publisher_house %>
        <%= f.collection_select :publisher_house_id, @houses, :id, :name %>
      </div>

      <div class="form-group">
        <%= f.label :pages %>
        <%= f.number_field :pages, class: "form-control" %>
      </div>

      <div class="form-group">
        <%= f.label :cover %>
        <%= f.text_field :cover, class: "form-control" %>
      </div>

      <div class="form-group">
        <%= f.label :published_at %>
        <%= f.date_select :published_at, class: "form-control", start_year: 1900, end_year: Date.today.year %>
      </div>

    </div>
    <div class="panel-footer text-right">
      <%= save_button %> |
      <% if (book.id.nil?) %>
        <%= cancel_button(books_path) %>
      <% else %>
        <%= cancel_button(book_path(book)) %>
      <% end %>
    </div>
  </div>
</div>
<% end %>

book_store/app/views/books/edit.html.erb
<% content_for :breadcrumb do %>
  <h2 class="col-xs-12"><%= books_home_link %> > <%= link_to(@book.title, @book) %> > Edit</h2>
<% end %>

<% content_for :main do %>
  <div class="row"> 
    <%= render 'form', book: @book %>
  </div>
<% end %>

book_store/app/views/books/index.html.erb
<% content_for :breadcrumb do %>
  <h2 class="col-xs-12"><%= books_home_link %> | Books</h2>
<% end %>

<% content_for :main do %>
  <div class="row">
    <div class="col-xs-12">
      <%= render '/shared/panel', title: 'Our Books', class_name: 'panel-success', big_title: true do %>
        <table class="table table-striped">
          <thead>
            <tr>
              <th class="col-xs-1"></th>
              <th>Title</th>
              <th>Publisher House</th>
              <th>Authors</th>
            </tr>
          </thead>

          <tbody>
          <% @books.each do |book| %>
            <tr>
              <td><img src="<%= book.cover %>" class="img-responsive"></td>
              <td><%= link_to(book.title, book) %></td>
              <td><%= link_to(book.publisher_house.name, book.publisher_house) %><br><%= book.published_at%></td>
              <td>
                <ul class="no-margin">
                <% book.sort_authors.each do |author| %>
                  <li><%= link_to(author.author_name, author) %></li>
                <% end %>
                </ul>
              </td>
            </tr>
          <% end %>
          </tbody>
        </table>
      <% end %>
    </div> 
  </div>
<% end %>

<% content_for :sidebar do %>
  <div class="row">
    <%= render '/shared/panel', title: 'Controls', class_name: 'panel-info', big_title: false do %>
      <%= create_icon_link_to(new_book_path) %>
    <% end %>
  </div>
<% end %>

book_store/app/views/books/new.html.erb
<% content_for :breadcrumb do %>
  <h2 class="col-xs-12"><%= books_home_link %> > New</h2>
<% end %>

<% content_for :main do %>
  <div class="row"> 
    <%= render 'form', book: @book %>
  </div>
<% end %>

book_store/app/views/books/show.html.erb
<% content_for :breadcrumb do %>
  <h2 class="col-xs-12"><%= books_home_link %> > <%= @book.title %></h2>
<% end %>

<% content_for :main do %>
  <div class="row">
    <div class="col-xs-12">
      <%= render '/shared/panel', title: 'My Details', class_name: 'panel-success', big_title: true do %>
        <div class="row">
          <div class="col-xs-3">
            <img src="<%= @book.cover %>" class="img-responsive">
          </div>
          <div class="col-xs-9">
            <h4><strong><%= @book.title %></strong></h4>
            <p>
              <strong>Publisher House:</strong>
              <%= link_to(@book.publisher_house.name, @book.publisher_house) %>
            </p>

            <p>
              <strong>Published at:</strong>
              <%= @book.published_at %>
            </p>

            <p>
              <strong>Pages:</strong>
              <%= @book.pages %>
            </p>

          </div>
        </div>
      <% end %>
    </div>
  </div>

  <div class="row">
    <div class="col-xs-12">
      <%= render '/shared/panel', title: 'My Authors', class_name: 'panel-info', big_title: true do %>
        <table class="table table-striped">
          <thead>
            <tr>
              <th>Name</th>
              <th>Birthdate</th>
              <th>Remove Author?</th>
            </tr>
          </thead>

          <tbody>
          <% @book.authors.each do |author| %>
            <tr>
              <td><%= link_to(author.author_name, author) %></td>
              <td><%= author.birthdate %></td>
              <td>
                <%= form_tag(collaboration_path, method: :delete) do %>
                  <%= hidden_field(:collaboration, :book_id, value: @book.id)%>
                  <%= hidden_field(:collaboration, :author_id, value: author.id)%>
                  <button type="submit" class="btn btn-danger btn-sm">
                      <span class="glyphicon glyphicon-remove" aria-hidden="true"></span>
                  </button>
                <% end %>
              </td>
            </tr>
          <% end %>
          </tbody>
        </table>
        <div class="col-xs-12">
          <h4>Add a new Author</h4>
          <div>
          <%= form_tag(collaboration_path, method: :post) do %>
            <%= hidden_field(:collaboration, :book_id, value: @book.id)%>
            <%= collection_select(:collaboration, :author_id, @authors, :id, :author_name, prompt: false)%>
            <button type="submit" class="btn btn-success btn-sm">
                <span class="glyphicon glyphicon-ok" aria-hidden="true"></span>
            </button>
          <% end %>
          </div>
        </div>
      <% end %>
    </div>
  </div>
<% end %>

<% content_for :sidebar do %>
  <div class="row">
    <%= render '/shared/panel', title: 'Controls', class_name: 'panel-info', big_title: false do %>
      <%= edit_icon_link_to(edit_book_path(@book)) %> | 
      <%= delete_icon_link_to(@book) %>
    <% end %>
  </div>
<% end %>